# Generated by Django 4.1.1 on 2022-10-25 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('nom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('sujet', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sujet')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Jour',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('titre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Jour',
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('titre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField(blank=True, null=True)),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapport_personne', to=settings.AUTH_USER_MODEL, verbose_name='Candidat(e)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Objectif',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('titre', models.CharField(max_length=100)),
                ('contenu', models.TextField(blank=True, max_length=200, null=True)),
                ('heure', models.TimeField(max_length=100)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('jour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jour')),
            ],
            options={
                'verbose_name': 'Objectif',
                'verbose_name_plural': 'Objectifs',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('titre', models.CharField(max_length=100)),
                ('resume', models.TextField(blank=True, max_length=200, null=True)),
                ('contenu', django_quill.fields.QuillField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cours')),
                ('statut', models.BooleanField(default=False)),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveau_cours', to='main.niveau')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_blog_comment', to='main.cours')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commentaire',
                'ordering': ['-created'],
            },
        ),
    ]
